# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: setup postgres service
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          TYPEORM_CONNECTION: postgres
          TYPEORM_HOST: localhost
          TYPEORM_USERNAME: superuser
          TYPEORM_PASSWORD: password
          TYPEORM_DATABASE: pyski-ci
          TYPEORM_PORT: 5432
          TYPEORM_SYNCHRONIZE: true
          TYPEORM_LOGGING: true
          TYPEORM_ENTITIES: lib/**/*.entity.ts
          TYPEORM_MIGRATIONS_DIR: lib/database/migrations
          TYPEORM_MIGRATIONS: lib/database/migrations/*.ts
        - run: npm ci
        - run: npm run bootstrap
        - run: npm run build --if-present
        - run: npm test
